openapi: 3.0.3

info:
  title: Duke Encounters API
  description: |
    **Duke Encounters** is a demo web application with a Spring Boot backend. It is using OpenAPI to generate all endpoints and models and requires a Keycloak.
  version: v1
  contact:
    name: Dominik Schadow
    email: dominikschadow@gmail.com
    url: https://github.com/dschadow/KeycloakSecurity
  license:
    url: https://github.com/dschadow/KeycloakSecurity/blob/main/LICENSE
    name: Apache License 2.0

servers:
  - url: 'http://localhost:8080'

tags:
  - name: EncounterOverview
    description: Public overview of all encounters without internal details
  - name: Encounter
    description: Authorized endpoints to modify and retrieve encounters with all details

paths:
  /v1/encounters-overview:
    get:
      description: Get a paginated list of all Duke encounters without internal details
      tags:
        - EncounterOverview
      operationId: readEncountersOverview
      responses:
        200:
          description: A list of Duke encounters without internal details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EncounterOverview'
  /v1/encounters:
    get:
      description: Get a paginated list of all Duke encounters with all details
      tags:
        - Encounter
      operationId: readEncounters
      security:
        - KeycloakToken: []
      responses:
        200:
          description: A list of Duke encounters with all details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Encounter'
    post:
      description: Create a new encounters entry
      tags:
        - Encounter
      operationId: createEncounter
      security:
        - KeycloakToken: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEncounter'
      responses:
        201:
          description: Successfully created a new encounter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Encounter'
  /v1/encounters/{encounter_id}:
    get:
      description: Get a single encounter
      tags:
        - Encounter
      operationId: readEncounter
      security:
        - KeycloakToken: []
      parameters:
        - name: encounter_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The encounter's ID
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
      responses:
        200:
          description: A single encounter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Encounter'

components:
  schemas:
    EncounterOverview:
      type: object
      description: Read only object containing a subset of Duke encounter details
      example:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        event: JavaOne
      properties:
        id:
          type: string
          format: uuid
        event:
          type: string
          minLength: 5
          maxLength: 50
    Encounter:
      type: object
      description: Represents a Duke encounter with all available details
      example:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        user_id: 3fa85f65-1234-4562-b3fd-1c963f66afa6
        event: JavaOne
        description: At the bar
        likeliness: 10
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        event:
          type: string
          minLength: 5
          maxLength: 50
        description:
          type: string
          maxLength: 1024
          nullable: true
        likeliness:
          type: integer
          minimum: 1
          maximum: 10
    CreateEncounter:
      type: object
      description: Create a new Duke encounter with all required information
      example:
        event: JavaOne
        description: At the bar
      properties:
        event:
          type: string
          minLength: 5
          maxLength: 50
        description:
          type: string
          maxLength: 1024
          nullable: true
    User:
      type: object
      description: Represents a user of the web application
      example:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        username: The Duke
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
          minLength: 3
          maxLength: 20
  securitySchemes:
    KeycloakToken:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:8090/oauth2/authorize
          tokenUrl: http://localhost:8090/oauth2/authorize
          scopes: {}
