openapi: 3.0.3

info:
  title: Keycloak Security API
  description: Keycloak Security API specification
  version: v1

servers:
  - url: 'http://localhost:8080'

paths:
  /v1/projects-overview:
    description: Get a paginated list of all projects without critical details
    get:
      tags:
        - ProjectOverview
      operationId: readProjectOverview
      responses:
        200:
          description: A list of projects without critical details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectOverview'
  /v1/projects:
    description: Get a paginated list of all projects with all details
    get:
      tags:
        - Project
      operationId: readProjects
      responses:
        200:
          description: A list of projects with all details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'

components:
  schemas:
    ProjectOverview:
      type: object
      description: Read only object containing a subset of project properties
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 5
          maxLength: 50
    Project:
      type: object
      description: Represents a project with all available properties
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        name:
          type: string
          minLength: 5
          maxLength: 50
        description:
          type: string
          maxLength: 1024
          nullable: true
        priority:
          type: integer
          minimum: 1
          maximum: 5
    User:
      type: object
      description: Represents a user of the web application
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
          minLength: 3
          maxLength: 20
