openapi: 3.0.3

info:
  title: Keycloak Security API
  description: Keycloak Security API specification
  version: v1

servers:
  - url: 'http://localhost:8080'

paths:
  /v1/projects-overview:
    description: Get a paginated list of all projects without critical details
    get:
      tags:
        - ProjectOverview
      operationId: readProjectOverview
      responses:
        200:
          description: A list of projects without critical details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectOverview'
  /v1/projects:
    description: Get a paginated list of all projects with all details
    get:
      tags:
        - Project
      operationId: readProjects
      responses:
        200:
          description: A list of projects with all details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'

components:
  schemas:
    ProjectOverview:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
          minLength: 5
          maxLength: 50
    Project:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
          minLength: 5
          maxLength: 50
        rating:
          type: integer
          minimum: 1
          maximum: 5
